project:
  type: website
  output-dir: docs

website:
  title: "HEMS Simulation Documentation"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Components"
        contents:
          - 01_web_application_interface__streamlit__.qmd
          - 02_simulation_engine__patient_journey__.qmd
          - 03_patient_entity_.qmd
          - 04_hems_resource_entity_.qmd
          - 05_resource_management__availability___allocation__.qmd
          - 06_stochastic_modeling__distributions__.qmd
          - 07_simulation_runner___parallelization_.qmd
          - 08_results_processing___visualization_.qmd

format:
  html:
    theme: cosmo
    toc: true
